// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const schemaPath = process.env.VERCEL || process.env.PRISMA_DATABASE_URL ? "prisma/schema.prisma" : "prisma/schema.sqlite.prisma";

export default defineConfig({
  schema: schemaPath,
  migrations: {
    path: "prisma/migrations",
  },
  // datasource: {
  //   url: process.env["DATABASE_URL"],
  // },
});
